-- PEN_LIST 테이블 생성 => 제조회사(COMPANY), 색상(COLOR)
-- PEN_LIST 테이블 출력
CREATE TABLE PEN_LIST (COMPANY VARCHAR2(20), COLOR VARCHAR2(20));
SELECT * FROM PEN_LIST;

-- PEN_LIST 테이블명 PEN으로 변경
ALTER TABLE PEN_LIST RENAME TO PEN;

-- PEN 테이블 중 COMPANY 칼럼명 COM으로 변경
ALTER TABLE PEN RENAME COLUMN COMPANY TO COM;

-- PEN 테이블에 굵기(THICKNESS) 칼럼 추가
-- PEN 테이블에 가격(PRICE) 칼럼 추가
ALTER TABLE PEN ADD THICKNESS FLOAT;
ALTER TABLE PEN ADD PRICE INT;

-- PEN 테이블 출력
SELECT * FROM PEN;

commit;

-- PEN 테이블에 대해 데이터 5-10개 삽입
INSERT INTO PEN(COM, COLOR, THICKNESS, PRICE) VALUES ('몽블랑', '블랙', 1.5, 700000);
INSERT INTO PEN(COM, COLOR, THICKNESS, PRICE) VALUES ('펠리칸', '블루', 2.0, 400000);
INSERT INTO PEN(COM, COLOR, THICKNESS, PRICE) VALUES ('파커', '실버', 0.5, 300000);
INSERT INTO PEN(COM, COLOR, THICKNESS, PRICE) VALUES ('파이롯트', '레드', 0.25, 200000);
INSERT INTO PEN(COM, COLOR, THICKNESS, PRICE) VALUES ('세일러', '그린', 0.3, 100000);

-- PEN 테이블 전체 데이터 출력
SELECT * FROM PEN;

COMMIT;

-- PEN 데이터 중, 가격이 2000원 이상인 데이터의 제조회사를 모두 '모나미'로 변경
UPDATE PEN SET COM ='모나미' WHERE PRICE >=2000;

-- PEN 데이터 중, 굵기가 0.5인 데이터의 가격을 1500으로 변경
UPDATE PEN SET PRICE = 1500 WHERE THICKNESS = 0.5;

-- PEN 테이블 전체 데이터 출력
SELECT * FROM PEN;

-- PEN 테이블 중 굵기, 색상 칼럼 데이터만 출력
SELECT THICKNESS, COLOR FROM PEN;
-- PEN 데이터 중, 색상이 'BLACK'인 데이터의 색상, 굵기, 가격 칼럼 데이터만 출력
SELECT COLOR, THICKNESS, PRICE FROM PEN WHERE COLOR = '블랙';

commit;

-- PEN 테이블의 모든 데이터 삭제
TRUNCATE TABLE PEN;
-- PEN 테이블 전체 출력
SELECT * FROM PEN;
-- PEN 테이블 전체 삭제
DROP TABLE PEN;

COMMIT;